import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import { ScrollToTop } from "./components/scroll_top";
import { SocialShare } from "./components/scrol_share";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="font-doto ">
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <div>
            <ScrollToTop />
            <SocialShare />
          </div>
      </body>
    </html>
  );
}
